### ISSUE TITLE
Produktnamen

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#1]
Guter Produkt Name. Beispiele vor.
"The system developed by the contractor must be given an appealing product name with high
recall value. The product name is used throughout the source code and documentation of
the system."

**Comment by Effizjens** [comment]
Meine Vorschläge:
1. ["Skylax"](https://de.wikipedia.org/wiki/Skylax)
2. ["Jason"](https://de.wikipedia.org/wiki/Jason) (Ist auch witzig wegen JSON)
3. ["Phokas"](https://de.wikipedia.org/wiki/Ioannis_Phokas)
4. ["Pytheas"](https://de.wikipedia.org/wiki/Pytheas)

Sind auch sortiert nach meinen Favoriten.

**Comment by bkari02** [comment]
Motherfuckinggoddamapplication

**Comment by SpeckiJ** [comment]
Meine Reihenfolge wäre 4 - 1 - 3 -2.
Wäre cool wenn man halt ein Akronym dazu haben würde - mir ist aber keins eingefallen was nicht hingekünstelt wirkt.

Mir selbst fallen nur so funktionale Dinge ein wie: 
 - PDIVS - Platform for Discovery, Interaction and Visualization of Sentinel Data

**Comment by Effizjens** [comment]
Wenn wir Skylax nehmen, könnten wir SLX als Abkürzung nehmen, ist zwar kein Akronym, aber was soll's ^^

**Comment by Thiemann96** [comment]
Finde 1 genial

**Comment by jasperbuss** [comment]
Bin für 1, finde 2 aber auch gut

**Comment by Effizjens** [comment]
Skylax ist gebongt!
