### ISSUE TITLE
JPEG2000 to MapTiles 

### ISSUE THREAD

**Issue by Thiemann96** [ling-js/skylax#12]
Man kann wohl über GDAL Bilder in verschiedene MapTiles transformieren welche wir uns dann über OpenLayers,Leaflet,..., anzeigen lassen können. Vielleicht weiß Specki da ja noch was zu wie GDAL funktioniert , du hattest ja den Vortrag dazu ? 
Habe es mir bisher nur sporadisch angeguckt , aber ist ja schonmal gut zu wissen das das gehen soll : http://www.klokan.cz/projects/gdal2tiles/

**Comment by SpeckiJ** [comment]
erstmal selber den "good issue" tag geben jaja 👍 

GDAL kann auf jeden Fall .jp2 lesen und in alle erdenklichen formate konvertieren. 
Die Frage ist welche Formate die Map (Leaflet oder Openlayers) akzeptiert!

**Comment by Effizjens** [comment]
Wollen wir denn das Bild dann als Basemap oder als Bild nehmen? Ich würde eher sagen, wir legen das dann als großes Bild auf eine Basemap oder?

**Comment by SpeckiJ** [comment]
Also wir nehmen ne Basemap und legen dann unsere "Bilder" mit einer variablen Transparenz (ist eine LF) dadrüber.

Wie machen wir das dann mit dem georeferenzieren von dem Bild? so ein .png was man da drüber legt hat ja keine Koordinaten die man auf der Karte verorten könnte.

**Comment by Effizjens** [comment]
Man kann doch bestimmt auch die Koordinaten trotzdem auslesen oder die Bildkoordinaten auslesen?

Hier ist ein Tutorial, ist das nicht das, was wir brauchen?
http://leafletjs.com/examples/crs-simple/crs-simple.html

**Comment by SpeckiJ** [comment]
> Sometimes, maps do not represent things on the surface of the earth and, as such, do not have a concept of geographical latitude and geographical longitude. 

Das ist bei uns ja nicht der Fall. Wir haben eine Basemap die die Welt darstellt. Und jetzt eine jp2 Datei die man da an der richtigen Stelle drüberlegen muss. Wenn wir die jp2 jetzt einfach in png umwandeln woher sollen wir dann noch wissen wo die eingezeichnet werden muss ? 

>  Koordinaten trotzdem auslesen 

Aus einem .jpeg oder .png kann man keine Koordinaten auslesen. Das Konzept von Koordinaten macht da ja gar keinen Sinn.

Daher brauchen wir halt irgendein Format in das wir das jp2 umwandeln was leaflet akzeptiert und wir quasi dann direkt einzeichnen können. - Oder dürfen wir uns selbst dann was basteln (json Object mit koordinaten + bild).

**Comment by SpeckiJ** [comment]
Bei ImageOverlay mit einer png brauchen wir halt noch zusätzlich Koordinaten.: [siehe hier](http://leafletjs.com/reference-1.2.0.html#imageoverlay)

Eric hatte ja TileLayer vorgeschlagen. [Dokumentation](http://leafletjs.com/reference-1.2.0.html#tilelayer)
