### ISSUE TITLE
Data Transfer: SocketIO.js vs. Websocket vs. No sockets at all

### ISSUE THREAD

**Issue by jasperbuss** [ling-js/skylax#13]
Basierend auf unserer Architektur würde ich socket.io vorschlagen, da ich gelesen habe, dass es bei Web Sockets zu Problemen mit load balancern kommen kann

**Comment by jasperbuss** [comment]
Basierend auf unserer Architektur würde ich socket.io vorschlagen, da ich gelesen habe, dass es bei Web Sockets zu Problemen mit load balancern kommen kann

**Comment by SpeckiJ** [comment]
Quelle der Infos ?
