### ISSUE TITLE
Sockets

### ISSUE THREAD

**Issue by jasperbuss** [ling-js/skylax#14]
Basierend auf unserer Architektur würde ich socket.io vorschlagen, da ich gelesen habe, dass es bei Web Sockets zu Problemen mit load balancern kommen kann.

**Comment by SpeckiJ** [comment]
Quelle ?

**Comment by jasperbuss** [comment]
https://www.heise.de/developer/artikel/Einfuehrung-in-Node-js-Folge-14-Websockets-3678891.html

wird am ende des videos erwähnt

**Comment by SpeckiJ** [comment]
Socket.IO nutzt intern auch nur WebSockets (Das ist das eigentliche Protokoll).

Laut offiziellem Wiki kann nginx WebSocket Verbindungen proxien: [Tutorial](https://www.nginx.com/blog/websocket-nginx/)
