### ISSUE TITLE
Anwendungsfälle

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#2]
Welche Anwendungsfälle gibt es?

**Comment by Effizjens** [comment]
Bauer will wissen, wie gut sein Land bewässert ist.
Baumbewuchs in einer bestimmten Region.

**Comment by bkari02** [comment]
# Use cases Skylax
1. Land change detection 

 Skylax can be used to detect land changes, as e.g. deforestation or building of new structures. Therefore you need to load in satellite images of different date and compare them by the use of fading images' opacity for example. This function supports the mapping of: 
 * Land cover development
 * Classification and change maps
 * Environmental analysis
 * Irrigated landscape mapping
 * Carbon Storage and Avoidance
 * Yield determination 
 * Soils and Fertility Analysis
 * And other accurate assessment of geophysical parameters
2. Insurance Industry
 
 Skylax can be used to detect and prove damages in the aftermath of natural phenomena. For example agriculture damages after flooding can be analyzed by calculating differences in vegetation indices of satellite images.
