### ISSUE TITLE
Zoom Level Restrictions

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#25]
Die API stellt die eingeblendeten Sentinel-Layer nur in den Zoomleveln 6-15 bereit. Momentan kann man noch weiter als Level 15 reinzoomen (damit verschwindet das Sentinel-Layer und man sieht nur noch die Background Map).

Eine Beschränkung der Leaflet Karte auf Zoomlevel 0-15 wäre wünschenswert.

**Comment by Effizjens** [comment]
"Fix for Zoom Level limit" hat die Beschränkung hinzugefügt.
