### ISSUE TITLE
remove ageInputName

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#26]
Momentan wird bei den Anfragen zum generieren des Servers noch ein Feld "ageInputName" mitgeschickt.

Dies ist so nicht vorgesehen (siehe Pflichtenheft) und führt beim Server zu einem Fehler.

**Comment by bkari02** [comment]
Ageinput ist der opacity-slider-Wert, sicher dass ich den rausnehmen soll bezüglich Permalinks und so wird das also sicher nicht gebraucht dass der mitgeschickt wird?

**Comment by SpeckiJ** [comment]
Permalinks kommen nicht in die "Processing-API" sondern in den Content Server. Die API kann damit nichts anfangen.

**Comment by Effizjens** [comment]
Ist das Problem noch aktuell?

**Comment by SpeckiJ** [comment]
API akzeptiert seit https://github.com/ling-js/skylax-api/commit/d39efd80385ef8f9b52c6fc59b186d6e32ff20f6 den Parameter nicht mehr. 

Ob das Frontend das noch mitschickt ist noch ungetestet.

**Comment by Effizjens** [comment]
Okay, ich habe das auch umbenannt, aber ich glaube, dass das nicht mehr mitgeschickt wird.
