### ISSUE TITLE
Opacity Slider

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#27]
Die Implementation des Opacity-Sliders (Durchsichtigkeit) für die Sentinel-Layer fehlt.

**Comment by bkari02** [comment]
Wo erzeugst du die Layer?

**Comment by SpeckiJ** [comment]
https://github.com/ling-js/skylax/blob/03f3b541ec9aabe615e994904ab864926cee30ad/public/javascripts/Load.js#L106

**Comment by Effizjens** [comment]
Erledigt mit https://github.com/ling-js/skylax/commit/6f5a1dfc2606cda0ae63bdfe50fccc16d88661ad
