### ISSUE TITLE
Enddate: Internal Server Error

### ISSUE THREAD

**Issue by bkari02** [ling-js/skylax#28]
Sobald man ein Enddate mit in die GET-Request gibt, wird ein Internal Server Error geschmissen. 
Fehlermeldung: 
>>>
Unable to filter by metadata: parsing time "" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "2006"
<<<
Was soll das bedeuten? und was für ein Datumsformat ist das in der Fehlermeldung mit "2006-01-02T15:04:05Z**07:00**" wo kommt das 07:00 her bzw. was soll das da?

**Comment by SpeckiJ** [comment]
Ich kümmere mich drum.

Die Stundenangabe gehört offiziell zum Format. In der Vergangenheit hat es aber auch immer ohne diese Angabe funktioniert (und nicht mit komischerweise.)

**Comment by bkari02** [comment]
Welche Stundenangabe? Bezieht sich das auf dieses komische "2006-01-02T15:04:05Z07:00"- Format? Die Stunden sind doch "2006-01-02T**15**:04:05Z07:00" und nicht das hinter dem Z?

Das Problem tritt übrigens auf sobald man irgendein Enddate mitschickt, Stunden, Minuten und Sekunden wurden im Startdate doch schon länger mit hochgeschickt bzw. da funktioniert es, bloß sobald irgendwas als Enddate mitgeschickt wird kommt der Fehler jetzt. Bis jetzt haben wir Enddate zwar in der Submitform als Eingabefeld eingebaut aber nie den Wert daraus, sondern immer einen leeren String als Enddate rausgeschickt (weil sonst der Fehler aus dem Issue hier kam)

**Comment by SpeckiJ** [comment]
Die Angabe hinter dem Z ist die Zeitzone nicht die Uhrzeit - da bin ich durcheinandergekommen. 

Bei Startdatum kommt der Fehler nicht auf?

**Comment by bkari02** [comment]
Ahh, ok. 
Nein, Startdatum ist im Format 2006-01-02T15:04:05Z und der Fehler erscheint nicht.

**Comment by SpeckiJ** [comment]
hopefully fixed in https://github.com/ling-js/skylax-api/commit/766b67b37b4616bf5f6743f5443f80c048a6998b
