### ISSUE TITLE
Uncaught TypeError durch Spinner

### ISSUE THREAD

**Issue by bkari02** [ling-js/skylax#29]
Der Spinner haut ein  Uncaught TypeError raus wenn man irgendwo auf die Karte klickt (eigentlich sollten dann die Koordinaten des Punktes wo man hinklickt geloggt werden). Fehler ist in spin.js:275 irgendwas mit Target.childNodes cannot read property of undefined 
@Invisible619

**Comment by Effizjens** [comment]
Das ist noch in da, als ich den Spinner getestet habe, weil wir noch keine Daten bekommen haben, ging er nicht mehr weg und man konnte ihn durch Klick auf die Karte entfernen. Die "spinner.hide()" Funktion kann da bei map on click entfernt werden.

**Comment by Effizjens** [comment]
Ich sehe gerade, dass da noch nicht meine Funktion zu Korrektur der Koordinaten eingebunden ist, also würdest du dann auch noch die falschen Koordinaten zurück bekommen, wenn du klickst.

**Comment by bkari02** [comment]
Solange ich nicht in andere Welten gehe habe ich doch die normalen Koordinaten oder? :D

**Comment by Effizjens** [comment]
Ja genau :D Aber falls du mal in anderen Welten gehst, weißt du, woran es liegt ^^

**Comment by bkari02** [comment]
Ich musste gerade auch noch in der folgenden Funktion die auskommentierte fette Zeile auskommentieren (also die war vorher halt nicht auskommentiert :D) weil es die id die der da abfragt wohl gar nicht gibt? Blickst du das @Invisible619 

function spinnerHide(target) {
  //Spinner Zeugs
  var spinnerList = target.childNodes;
  for (var i = 0; i < spinnerList.length; i++) {
    if (spinnerList[i].className == 'spinner' && toggler == true) {
      target.removeChild(spinnerList[i]);
      document.getElementById('searchIt').disabled = false;
      **//document.getElementById('formSubmiter').disabled = false;**
      toggler = false;
      break;
    }
  }
}



& das mit deiner Koordinaten Korrekturfunktion überlass ich dann dir die da einzufügen oder nicht bei dem onClick dingen :D

**Comment by Effizjens** [comment]
Sollte jetzt behoben sein mit https://github.com/ling-js/skylax/commit/748312accc4cd929e6120f4ebd80d6b2efc8877c, probier einfach nochmal aus, was du gerade gemacht hast :)
