### ISSUE TITLE
Funktionalen Anforderungen

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#3]
Wie werden die funktionalen Anforderungen umgesetzt?

**Comment by SpeckiJ** [comment]
[functionaleanforderungen.pdf](https://github.com/ling-js/skylax/files/1405393/functionaleanforderungen.pdf)

**Comment by SpeckiJ** [comment]
Revision 2:

[functionaleanforderungen_v02.pdf](https://github.com/ling-js/skylax/files/1444286/functionaleanforderungen_v02.pdf)

**Comment by SpeckiJ** [comment]
Revision 3:

[functionaleanforderungen_v03.pdf](https://github.com/ling-js/skylax/files/1472868/functionaleanforderungen_v03.pdf)

**Comment by SpeckiJ** [comment]
Revision 4:

[functionaleanforderungen_v04.pdf](https://github.com/ling-js/skylax/files/1634723/functionaleanforderungen_v04.pdf)

**Comment by SpeckiJ** [comment]
Revision 5:

[functionaleanforderungen_v05.pdf](https://github.com/ling-js/skylax/files/1649225/functionaleanforderungen_v05.pdf)

**Comment by Thiemann96** [comment]
[Manual_Skylax.pdf](https://github.com/ling-js/skylax/files/1671254/Manual_Skylax.pdf)

**Comment by Thiemann96** [comment]
[Manual_Skylax.pdf](https://github.com/ling-js/skylax/files/1671274/Manual_Skylax.pdf)

**Comment by SpeckiJ** [comment]
Revision 6 (final):

[product_specification_skylax.pdf](https://github.com/ling-js/skylax/files/1671402/product_specification_skylax.pdf)
