### ISSUE TITLE
Anzeige der Bounding Boxen 

### ISSUE THREAD

**Issue by Thiemann96** [ling-js/skylax#30]
Bounding Boxen werden  für jede Page ( à 8 ) auf der Map erstellt. Was noch dahingehend zu erledigen ist:

- Sobald auf eine Box geklickt wird öffnet sich das korrespondierende Akkordion 
- Sobald auf ein Dataset "show this dataset" geklickt wird , wird auf diese Box gezoomt 
- Tooltips erstellen ,sodass wenn man über eine Box mit der Maus geht angezeigt wird um welches Dataset es sich handelt.

**Comment by Effizjens** [comment]
https://github.com/ling-js/skylax/commit/ecb9306fae80f27220b76b3a9d44363f5f012bed
