### ISSUE TITLE
bbox Parameter

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#32]
Momentan wird der bbox Parameter in der folgenden Form abgeschickt:

bbox="0,0,1,1"

es müsste richtig heissen:

bbox=0,0,1,1

**Comment by bkari02** [comment]
done. Aber funktioniert immer noch nicht, jetzt erscheint ein open error:

GET http://gis-bigdata.uni-muenster.de:14014/search?substring=&bbox=7.426757812500001,48.777912755501845,12.656250000000002,52.96187505907603&startdate=2015-01-01T00:00:00Z&enddate=&page=0 500 (Internal Server Error)
index.js:110 

Achtung:Es gab einen Fehler bei der AJAX-Anfrage der Fehlercode lautet :Unable to filter by metadata: Error: dataset '/opt/sentinel2/S2A_MSIL2A_20170410T103021_N0204_R108_T32TMR_20170410T103020.SAFE/MTD_MSIL1C.xml' open error

**Comment by SpeckiJ** [comment]
Okay. Werde ich morgen fixen.

die API unterstützt aktuell keine S2A Metadaten - die hat er bisher nie gebraucht erst jetzt wenn das filtern funktioniert versucht er die jetzt auszulesen.

**Comment by SpeckiJ** [comment]
Temporäres Workaround:

Sobald filter (bbox oder datum) genutzt wird werden Level-2A Datasets ignoriert. Betrifft im Testdatensatz exakt 1 Element.

Fix: Wenn S2A Support implementiert ist.

**Comment by SpeckiJ** [comment]
fixed in https://github.com/ling-js/skylax-api/commit/7f3b1247fffae15bf300d03aac2981f11d07bddd
