### ISSUE TITLE
Permalink

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#38]
Permalinks erstellen wie in F02020 beschrieben. 

https://github.com/ling-js/skylax/commit/704163a13e2f5a41a1d4757fa0725e1f9584d5ab

**Comment by SpeckiJ** [comment]
Client-seitig:

Funktion um alle Variablen in JSON Objekt zu exportieren.
Funktion um alle Variablen aus JSON Objekt zu laden

In Pug:

Variable hinzufuegen
clientseitiges Laden des Objektes wenn nicht leer

Server-Seitig:

Alter Pfad -> Setzen der Pug variable auf ""
Neuer Pfad mit 1 Parameter -> Setzen der Pug variable auf Parameter

**Comment by SpeckiJ** [comment]
Implemented in https://github.com/ling-js/skylax/commit/2cf2631fe3de867700dbee84bf695b0256176c89
