### ISSUE TITLE
Mockups

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#4]
Wie wird das System grob für Nutzer aussehen? (→Mockups, UI diagramm)

**Comment by Effizjens** [comment]
@jasperbuss macht das Zuende!

**Comment by jasperbuss** [comment]
Ich mach dich gleich zu ende!

**Comment by SpeckiJ** [comment]
![mainmockup](https://user-images.githubusercontent.com/13851077/31866807-6378788a-b785-11e7-9477-8cec1989539d.jpeg)

![whatsapp image 2017-10-20 at 10 57 26](https://user-images.githubusercontent.com/13851077/31866811-7c10cca8-b785-11e7-8d42-97b43b9f7bab.jpeg)
