### ISSUE TITLE
ValueLookup

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#45]
since v0.5 the API also supports requests to /value for looking up the original measurement on a specific coordinate.

The usage of this feature is required by L01080.

Details can be found in the functionaleanforderungen in the wiki.

**Comment by Effizjens** [comment]
What do you mean with Bandname? If you select RGB, there is more than one bandname, isn't it?

**Comment by SpeckiJ** [comment]
3 Bandnames -> 3 seperate Reqests :)
