### ISSUE TITLE
No Polygon preview for L2A Datasets

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#48]
there is currently no preview (red boxes) for L2A Datasets.

**Comment by Effizjens** [comment]
The drawPolygon function calls the stringToCoordArraystring function. I guess, the Footprint is different in L2A Datasets. Do you have an example for an L2A Dataset?

**Comment by Effizjens** [comment]
https://github.com/ling-js/skylax/commit/be6b19f4534706907c64c10a26951b6bb3aa6f56
Should work now, please test it

**Comment by SpeckiJ** [comment]
Thanks for fixing this :)
