### ISSUE TITLE
Show Metadata with onclick

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#49]
> Users get further Information and metadata of images when they select an image [...] in the map (LF00060)

This needs to be implemented. Currently there is only a small popup showing the Dataset Name. This needs to be expanded to automatically open the associated accordion in the sidebar and scroll to it.

**Comment by Effizjens** [comment]
There is already a openAccordion() function in Load.js. The metadata accordion will popout, when clicked on the polygon.

**Comment by Effizjens** [comment]
I don't know, how you can set the scroll level of the sidebar...

**Comment by Effizjens** [comment]
https://github.com/ling-js/skylax/commit/c4cf4989d8c6e0af2f6524af30fe5559b897a6f5
Found a way

**Comment by SpeckiJ** [comment]
thanks for the implementation @Effizjens
