### ISSUE TITLE
Systemarchitektur 

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#5]
Wie sieht die Systemarchitektur aus?

**Comment by SpeckiJ** [comment]
# Vorschlag:


![system_architecture](https://user-images.githubusercontent.com/13851077/31639008-db859b68-b2d6-11e7-9c7d-cb7d173c572b.png)

## Vorschlag für konkreten Komponenten:
 - Clients: beliebige Browser
 - Load Balancer: nginx Server (als Reverse Proxy)
 - CDN: nodejs Server (liefert statischem Website content (HTML + Javascript))
 - Processing: golang Server (liefert API für Kartendaten + Suche + Processing)
 - External Datasource: bereitgestellte Datenquelle oder wahlweise AWS S3.

## Vorteile: 
 - Load balancing -> Aufwendige Operation hält nicht das ganze System auf sondern nur einen Server.
 - Processing beliebig skalierbar -> weitere Server (evtl. sogar dynamisch) hinzufügbar falls Rechenleistung nicht ausreicht
 - CDN skaliert unabhängig von Processing -> braucht man ja auch deutlich weniger (muss ja nur statischen Content wegschicken)

## Nachteile: 
 - aufwendiger als 1 Server für alles

**Comment by Thiemann96** [comment]
Find ich gut

**Comment by Effizjens** [comment]
Ist abgesegnet!
