### ISSUE TITLE
Tile Layer Bounds

### ISSUE THREAD

**Issue by SpeckiJ** [ling-js/skylax#54]
Currently Leaflet is requesting Tiles that are not present on the Server. This leads to a lot of unnecessary Requests and possible delays due to rate-limitations (when requesting a lot of invalid tiles requests for real tiles may be delayed).

This can be fixed by setting the Layer Bounds for the Tile Layer. See:

http://leafletjs.com/reference-1.3.0.html#tilelayer-bounds

**Comment by Effizjens** [comment]
When a dataset ist loaded, a invisible polygon is created (drawInvisPolygon). Think that can be usefull for this.

**Comment by Effizjens** [comment]
Max-MinZoom is also possible for tile layers. The min, max Zoom for the map could be deleted, if it would be implemented here.

**Comment by SpeckiJ** [comment]
> Max-MinZoom is also possible for tile layers. The min, max Zoom for the map could be deleted, if it would be implemented here.

I am against specifying the min/maxZoom for the Layer instead of the whole Map.
This would enable users to zoom further in/out and have the dataset disappearing/reappearing without any explanation.

> The min, max Zoom for the map could be deleted

The min and maxZoom of the Map is currently different from the configuration of the API. The alignment of the API with the Frontend also needs to be done

**Comment by Effizjens** [comment]
But datasets do disappear in the moment, when zooming out.
I believe, if we would set the MinMax zoom of the map the zoom levels, where datasets can be seen, is to small for a good use of the map.
Maybe we could paint on the invisible polygon when the dataset disappears, so the user knows, that it's still there.

**Comment by SpeckiJ** [comment]
@Effizjens is this fully implemented ?

**Comment by Effizjens** [comment]
Yes with https://github.com/ling-js/skylax/commit/5d5e30610d1f5597ebb98b7bfa0b0796e54fae5f
