### ISSUE TITLE
Technologien 

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#6]
Welche Technologien werden benutzt?

**Comment by SpeckiJ** [comment]
# Vorschlag:
Basiert auf Vorschlag für Systemarchitektur in #5 

## Development
 - [yarn](https://yarnpkg.com/lang/en/)
 - Github

## Client-seitig:
 - jquery + AJAX
 - (Vue.js)
 - Bootstrap
 - Leaflet

## Server-seitig:
 - [nginx Proxy Server](https://nginx.org/)
 - [Nodejs Server](https://nodejs.org/)
   - [Express Middleware](http://expressjs.com/)
   - (...)
 - [golang Server](https://golang.org/)
   - general framework: [gorilla](http://www.gorillatoolkit.org/)
   - data format conversion + map cropping: [go-gdal](https://github.com/ksshannon/go-gdal)
   - caching: [go-cache](https://github.com/patrickmn/go-cache) and/or [groupcache](https://github.com/golang/groupcache)
   - (...)
 - (...)
