### ISSUE TITLE
Incomplete project requirements

### ISSUE THREAD

**Issue by bkari02** [ling-js/skylax#61]
These are the requirements that we did not yet completed: (27th of January 2018)

- Spinner on TCI Image is missing //DONE
- /LF00050/ - Sorting by date is still missing
- All Bonus Features are missing
- Non-Functional: 
- Portability: Tooltips function in Chrome is not working
- Maintainability: Dependency Management (Needed?)
- Deliveries: User manual is missing & Report on the fulfillment of functional requirements

**Comment by bkari02** [comment]
Error function of bounding box inputs doesn't work correct

**Comment by SpeckiJ** [comment]
- Remove console.logs
- TCI Opacity Slider //DONE
- TCI Valuelookup //DONE

**Comment by bkari02** [comment]
& See styling issues #46

**Comment by SpeckiJ** [comment]
[fulfilment_functional_requirements.pdf](https://github.com/ling-js/skylax/files/1673630/fulfilment_functional_requirements.pdf)

**Comment by SpeckiJ** [comment]
done
