### ISSUE TITLE
Risiken 

### ISSUE THREAD

**Issue by Effizjens** [ling-js/skylax#7]
Welche Risiken gibt es?

**Comment by Thiemann96** [comment]
- Wir sind uns im unklaren ob GDAL die JPEG2000-Dateien in angemessener Zeit in die von uns gewünschten Map Tiles konvertieren kann.
 - GoLang Server als WMS , ist dies überhaupt möglich?
 - Bildverarbeitung in GoLang (Pixelbasis ) für arithmetische Funktionen > Bibliotheken ? 
 - Wie verhält es sich mit der Performance von Leaflet ? Was fragt Leaflet an , wie arbeitet Leaflet ? 
 - Wie aufwändig ist die Suche direkt auf das filesystem ? Evtl. eigene Datenbanken mit Metadaten erstellen ?
